// a11ign/a11ign#3452: wakes per merged row. Fixtures only: nothing here reads `~/.claude`, `~/.cache/a11ign` or GitHub.
// no-token: gh -- every source is an injected fixture; the only `gh` calls in the module are `readMergedPulls`'s default and `readClaimedAt`; the tests inject `readMergedPulls`'s reader and call no other
// The worker-3390 fixture is the worked example on the row, in the real record shape (a `user` record whose string content is wrapped in `<pasted_content`).
import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { chmodSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { fileURLToPath } from "node:url";
import {
  compareReadings, dailyMeans, isWake, matchLedger, measure, parseArgs, parseLedger, parseTranscript, readMergedPulls, renderReading, reviewerTarget, rowsClosedBy, workerRowFor,
} from "./wakes-per-row.mjs";

const at = (iso) => Date.parse(iso);
const WINDOW = { from: at("2026-10-04T00:00:00Z"), to: at("2026-10-04T13:00:00Z") };

// ---- the record shapes, as the harness writes them -----------------------------------------------------------------------------------------------------
const user = (timestamp, content, extra = {}) => JSON.stringify({ type: "user", timestamp, message: { role: "user", content }, ...extra });
const wakeText = (session, body) => `<pasted_content id="f277">\nYou are \`${session}\` -- ${body}\n</pasted_content>`;
const FIRST_ORDER = `\n\n${wakeText("worker-3390", "an org session in this repository.")}`;
const toolResult = (timestamp) => user(timestamp, [{ type: "tool_result", tool_use_id: "toolu_1", content: "ok" }]);

const NON_WAKES = {
  "/compact": user("2026-10-04T11:07:30.000Z", "/compact"),
  "a local-command echo": user("2026-10-04T11:07:31.000Z", "<local-command-stdout>Compacted</local-command-stdout>"),
  "a local-command caveat": user("2026-10-04T11:07:31.500Z", "<local-command-caveat>Caveat: the messages below were generated by the user while running local commands.</local-command-caveat>"),
  "the continuation summary": user("2026-10-04T11:08:09.264Z", "This session is being continued from a previous conversation that ran out of context.", { isCompactSummary: true }),
  "a meta record": user("2026-10-04T11:07:32.057Z", "<pasted_content id=\"zz\">meta</pasted_content>", { isMeta: true }),
  "a tool result": toolResult("2026-10-04T11:00:00.000Z"),
};

/** The three deliveries of the worked example, plus everything that is not one, in the order the transcript has them. */
function worker3390Transcript() {
  return [
    user("2026-10-04T10:37:49.502Z", FIRST_ORDER),
    toolResult("2026-10-04T10:40:00.000Z"),
    toolResult("2026-10-04T11:05:00.000Z"),
    NON_WAKES["/compact"],
    NON_WAKES["a local-command caveat"],
    NON_WAKES["a local-command echo"],
    NON_WAKES["the continuation summary"],
    user("2026-10-04T11:08:10.282Z", wakeText("worker-3390", "a follow-up order: #3390 IS YOURS AND IS NO LON")),
    toolResult("2026-10-04T11:09:00.000Z"),
    user("2026-10-04T12:07:16.335Z", `\n\n${wakeText("worker-3390", "IDLE FOR 46 MINUTES WITH NO WAIT")}`),
  ].join("\n");
}

const LEDGER_3390 = [
  "1791110269175\tengineers/ready-row-unclaimed/3390\tworker-3390",
  "1791110380727\tRESET\tengineers/ready-row-unclaimed/3390",
  "1791112056764\tworker-3390/blocker-cleared/row-3390/3384\t\tno-clear",
  "1791115636021\tworker-3390/claim-stalled/row-3390/nudge-1791115602237\t\tno-clear",
].join("\n");

const PR_134 = { repo: "a11ign/agent-org", number: 134, createdAt: "2026-10-04T11:06:00Z", mergedAt: "2026-10-04T11:19:39Z", body: "Closes a11ign/a11ign#3390\n" };
const INSTANCE_3390 = { session: "worker-3390", rows: [3390], spawnedAt: at("2026-10-04T10:37:49.168Z"), endedAt: null };
const ROW_REPO = "a11ign/a11ign";
const CLAIMED = new Map([[3390, at("2026-10-04T10:35:57Z")]]);

const run = (overrides = {}) => measure({
  window: WINDOW,
  pulls: [PR_134],
  transcripts: [parseTranscript(worker3390Transcript(), "w3390.jsonl")],
  ledger: parseLedger(LEDGER_3390),
  instances: [INSTANCE_3390],
  claimedAt: CLAIMED,
  rowRepo: ROW_REPO,
  ...overrides,
});

// ---- (1) the worked example ----------------------------------------------------------------------------------------------------------------------------
test("worker-3390: 3 wakes and 1 compaction, 2 after the pull request opened, 1 after it merged", () => {
  const transcript = parseTranscript(worker3390Transcript(), "w3390.jsonl");
  assert.equal(transcript.ok, true);
  assert.equal(transcript.wakes.length, 3);
  assert.equal(transcript.compactions, 1);
  assert.equal(transcript.session, "worker-3390");

  const reading = run();
  assert.equal(reading.mergedRows, 1);
  assert.equal(reading.attributedWakes, 3);
  assert.equal(reading.wakesPerRow.mean, 3);
  assert.equal(reading.afterOpened, 2);
  assert.equal(reading.afterMerged, 1);
  assert.equal(reading.compactions, 1);
  assert.deepEqual(reading.byCause, { "ready-row-unclaimed": 1, "blocker-cleared": 1, "claim-stalled": 1 });
  assert.equal(reading.remainder.total, 0);
});

test("worker-3390: the two wakes that named a cause already false when typed are counted as stale, the first order is not", () => {
  assert.equal(run().stale, 2);
});

test("bytes per wake is the delivered text, measured per wake", () => {
  const transcript = parseTranscript(worker3390Transcript(), "w3390.jsonl");
  const expected = transcript.wakes.reduce((sum, wake) => sum + wake.bytes, 0) / 3;
  assert.equal(run().bytesPerWake, expected);
  assert.ok(expected > 0);
});

// ---- (2) what is not a wake, each as its own case ------------------------------------------------------------------------------------------------------
for (const [name, line] of Object.entries(NON_WAKES)) {
  test(`${name} is not a wake`, () => {
    assert.equal(parseTranscript(line, "x.jsonl").wakes.length, 0);
    assert.equal(parseTranscript(`${line}\n${user("2026-10-04T12:00:00Z", wakeText("worker-1", "order"))}`, "x.jsonl").wakes.length, 1, "positive control: the real wake beside it is counted");
  });
}

test("isWake reads the wrapper, not the word compact", () => {
  assert.equal(isWake(JSON.parse(NON_WAKES["/compact"])), false);
  assert.equal(isWake(JSON.parse(user("2026-10-04T12:00:00Z", wakeText("worker-1", "order")))), true);
});

// ---- (3) a wake after the instance ended belongs to no row, and is printed ----------------------------------------------------------------------------
test("a wake delivered after the instance ended is the remainder, not the row's and not dropped", () => {
  const ended = { ...INSTANCE_3390, endedAt: at("2026-10-04T11:30:00Z") };
  const reading = run({ instances: [ended] });
  assert.equal(reading.attributedWakes, 2);
  assert.equal(reading.remainder.total, 1);
  assert.deepEqual(reading.remainder.bySession, { "worker-3390": 1 });
  assert.deepEqual(reading.remainder.byReason, { "after-instance-ended": 1 });
});

test("attribution is by claim: with the instance still holding the row, a wake after the merge stays with the row", () => {
  const reading = run();
  assert.equal(reading.rows[0].wakes, 3);
  assert.equal(reading.rows[0].afterMerged, 1);
});

test("a worker holding two rows gives each wake to the latest-claimed row at or before it", () => {
  const two = { session: "worker-9", rows: [10, 20], spawnedAt: null, endedAt: null };
  const claimed = new Map([[10, 1000], [20, 2000]]);
  assert.deepEqual(workerRowFor({ at: 1500, bytes: 1, session: "worker-9" }, [two], claimed), { row: 10 });
  assert.deepEqual(workerRowFor({ at: 2500, bytes: 1, session: "worker-9" }, [two], claimed), { row: 20 });
  assert.deepEqual(workerRowFor({ at: 500, bytes: 1, session: "worker-9" }, [two], claimed), { reason: "before-any-claim" });
});

test("a wake on a row that did not merge in the window is the remainder, with its own reason", () => {
  const other = { session: "worker-5", rows: [5], spawnedAt: null, endedAt: null };
  const transcript = parseTranscript(user("2026-10-04T09:00:00Z", wakeText("worker-5", "order")), "w5.jsonl");
  const reading = run({ transcripts: [parseTranscript(worker3390Transcript(), "a"), transcript], instances: [INSTANCE_3390, other], claimedAt: new Map([[3390, 0], [5, 0]]) });
  assert.deepEqual(reading.remainder.byReason, { "on-a-row-not-merged-in-the-window": 1 });
});

// ---- reviewers -----------------------------------------------------------------------------------------------------------------------------------------
test("a reviewer's wakes belong to the row its pull request closes, inside the pull request's window only", () => {
  const reviewer = [
    user("2026-10-04T11:10:00Z", wakeText("reviewer-agent-org-134", "review")),
    user("2026-10-04T11:15:00Z", wakeText("reviewer-agent-org-134", "re-review")),
    user("2026-10-04T11:30:00Z", wakeText("reviewer-agent-org-134", "after merge")),
  ].join("\n");
  const reading = run({ transcripts: [parseTranscript(worker3390Transcript(), "a"), parseTranscript(reviewer, "r.jsonl")] });
  assert.equal(reading.rows[0].reviewerWakes, 2);
  assert.equal(reading.rows[0].workerWakes, 3);
  assert.deepEqual(reading.remainder.byReason, { "reviewer-outside-its-pull-request-window": 1 });
});

test("reviewerTarget names the repository and the number", () => {
  assert.deepEqual(reviewerTarget("reviewer-3402", ROW_REPO), { repo: "a11ign/a11ign", number: 3402 });
  assert.deepEqual(reviewerTarget("reviewer-agent-org-141", ROW_REPO), { repo: "a11ign/agent-org", number: 141 });
  assert.equal(reviewerTarget("worker-3390", ROW_REPO), null);
  assert.equal(reviewerTarget("ceo", ROW_REPO), null);
  assert.deepEqual(reviewerTarget("reviewer-tool-9", "acme/board"), { repo: "acme/tool", number: 9 });
  // A key is [a-z0-9-] and never ends in -<digits> (project-config.mjs), so a digit inside it is a key, and the number is the last run of digits.
  assert.deepEqual(reviewerTarget("reviewer-tool2-9", "acme/board"), { repo: "acme/tool2", number: 9 });
  assert.deepEqual(reviewerTarget("reviewer-3d-viewer-12", "acme/board"), { repo: "acme/3d-viewer", number: 12 });
  assert.deepEqual(reviewerTarget("reviewer-12", "acme/board"), { repo: "acme/board", number: 12 });
  // A key ending in -<digits> is refused by the declaration, so the name is no reviewer's rather than a reviewer of "tool-2".
  assert.equal(reviewerTarget("reviewer-tool-2-9", "acme/board"), null);
});

// ---- (4) a standing lead is its own line ---------------------------------------------------------------------------------------------------------------
test("a standing lead's wakes are printed as their own line with a count, never added to a row", () => {
  const lead = [user("2026-10-04T09:00:00Z", wakeText("ceo", "tick")), user("2026-10-04T09:30:00Z", wakeText("ceo", "tick"))].join("\n");
  const reading = run({ transcripts: [parseTranscript(worker3390Transcript(), "a"), parseTranscript(lead, "ceo.jsonl")] });
  assert.deepEqual(reading.remainder.bySession, { ceo: 2 });
  assert.deepEqual(reading.remainder.byReason, { "standing:ceo": 2 });
  assert.equal(reading.attributedWakes, 3);
  assert.match(renderReading(reading), /REMAINDER \(no merged row\): 2 wakes; by session \{"ceo":2\}/);
});

test("a remainder wake outside the window is not counted in it", () => {
  const lead = user("2026-10-03T09:00:00Z", wakeText("ceo", "yesterday"));
  assert.equal(run({ transcripts: [parseTranscript(worker3390Transcript(), "a"), parseTranscript(lead, "ceo.jsonl")] }).remainder.total, 0);
});

// ---- (5) unreadable is UNMEASURED, never zero ----------------------------------------------------------------------------------------------------------
test("an unreadable transcript is reported unreadable and its row UNMEASURED, never zero wakes", () => {
  const broken = `${user("2026-10-04T10:37:49.502Z", FIRST_ORDER)}\n{"type":"user","timestamp":`;
  const transcript = parseTranscript(broken, "broken.jsonl");
  assert.equal(transcript.ok, false);
  assert.equal(transcript.session, "worker-3390", "an unreadable file still says whose it was");
  const reading = run({ transcripts: [transcript] });
  assert.equal(reading.measuredRows, 0);
  assert.equal(reading.wakesPerRow.mean, null);
  assert.equal(reading.rows[0].measured, false);
  assert.match(reading.unmeasured[0].reason, /worker-3390: a transcript is unreadable/);
  assert.equal(reading.unreadableTranscripts.length, 1);
  assert.match(renderReading(reading), /UNMEASURED row #3390/);
});

test("a claimant with no transcript at all is UNMEASURED, and a row nobody is recorded as holding is too", () => {
  assert.match(run({ transcripts: [] }).unmeasured[0].reason, /no transcript found/);
  assert.match(run({ instances: [] }).unmeasured[0].reason, /no claimant recorded/);
});

test("an UNMEASURED row stays out of the mean and median of the measured ones", () => {
  const second = { ...PR_134, number: 135, body: "Closes a11ign/a11ign#3391\n" };
  const reading = run({ pulls: [PR_134, second] });
  assert.equal(reading.mergedRows, 2);
  assert.equal(reading.measuredRows, 1);
  assert.equal(reading.wakesPerRow.mean, 3, "the unmeasured row is not averaged in as 0");
  assert.equal(reading.wakesPerRow.median, 3);
});

// ---- (6) the ledger and the transcript are one wake ----------------------------------------------------------------------------------------------------
test("a wake seen in the ledger and the transcript is one wake, and a ledger line with no wake is reported apart", () => {
  const reading = run();
  assert.equal(reading.attributedWakes, 3, "3 transcript wakes + 3 ledger lines is 3, not 6");
  assert.equal(reading.ledgerOnly, 0);
  const extra = `${LEDGER_3390}\n1791113000000\tworker-3390/blocker-cleared/row-3390/9999\t\tno-clear`;
  const withExtra = run({ ledger: parseLedger(extra) });
  assert.equal(withExtra.attributedWakes, 3);
  assert.equal(withExtra.ledgerOnly, 1);
});

test("matchLedger pairs the nearest earlier line once, and leaves a wake with no line as cause unknown", () => {
  const wakes = [{ at: 100_000, bytes: 1, session: "s" }, { at: 200_000, bytes: 1, session: "s" }];
  const entries = [{ at: 99_000, key: "s/a/1", session: "s", cause: "a" }];
  const { wakes: labelled, unmatched } = matchLedger(wakes, entries);
  assert.deepEqual(labelled.map((wake) => wake.cause), ["a", "unknown"]);
  assert.equal(unmatched.length, 0);
});

test("parseLedger skips RESET, ESCALATED and blank lines, and reads the session of an `engineers` order from its third field", () => {
  const entries = parseLedger(LEDGER_3390 + "\n\n1791119360112\tESCALATED\tworker-1/x/1\n");
  assert.deepEqual(entries.map((entry) => [entry.session, entry.cause]), [["worker-3390", "ready-row-unclaimed"], ["worker-3390", "blocker-cleared"], ["worker-3390", "claim-stalled"]]);
});

// ---- rows, windows, comparison -------------------------------------------------------------------------------------------------------------------------
test("rowsClosedBy: `Closes: none` closes nothing, a list closes each, another repository's issue is not a row", () => {
  assert.deepEqual(rowsClosedBy("Closes: none -- a11ign/a11ign#3390 stays open\n", ROW_REPO), []);
  assert.deepEqual(rowsClosedBy("Closes #1, #2 and a11ign/a11ign#3\nCloses other/repo#4\n", ROW_REPO), [1, 2, 3]);
  assert.deepEqual(rowsClosedBy("nothing here", ROW_REPO), []);
  // Positive control: the repository is an argument, not a constant -- the same body names a row of one project and none of another's.
  assert.deepEqual(rowsClosedBy("Closes acme/board#7\n", "acme/board"), [7]);
  assert.deepEqual(rowsClosedBy("Closes acme/board#7\n", ROW_REPO), []);
});

test("a pull request merged outside the window closes no row in it", () => {
  const early = { ...PR_134, mergedAt: "2026-10-03T11:19:39Z" };
  assert.equal(run({ pulls: [early] }).mergedRows, 0);
});

test("dailyMeans groups by UTC merge day", () => {
  const days = dailyMeans([
    { mergedAt: at("2026-10-01T10:00:00Z"), wakes: 2 }, { mergedAt: at("2026-10-01T23:00:00Z"), wakes: 4 }, { mergedAt: at("2026-10-02T01:00:00Z"), wakes: 6 },
  ]);
  assert.deepEqual(days, [{ day: "2026-10-01", rows: 2, mean: 3 }, { day: "2026-10-02", rows: 1, mean: 6 }]);
});

test("compareReadings: a difference inside the before window's day-to-day spread is no measurable change", () => {
  const before = { wakesPerRow: { mean: 4 }, bytesPerWake: 1000, daily: [{ mean: 3 }, { mean: 5 }, { mean: 4 }] };
  assert.equal(compareReadings(before, { wakesPerRow: { mean: 3 }, bytesPerWake: 900 }).verdict, "no measurable change");
  const better = compareReadings(before, { wakesPerRow: { mean: 1.5 }, bytesPerWake: 900 });
  assert.equal(better.verdict, "improved");
  assert.equal(better.wakesDelta, -2.5);
  assert.equal(better.bytesDelta, -100);
  assert.equal(compareReadings(before, { wakesPerRow: { mean: 7 }, bytesPerWake: 900 }).verdict, "worse");
  assert.equal(compareReadings(before, { wakesPerRow: { mean: null }, bytesPerWake: null }).verdict, "unmeasured");
});

test("parseArgs refuses a missing or inverted window", () => {
  assert.throws(() => parseArgs([]), /usage/);
  assert.throws(() => parseArgs(["--from", "2026-10-05T00:00:00Z", "--to", "2026-10-04T00:00:00Z"]), /from < to/);
  assert.deepEqual(parseArgs(["--from", "2026-10-01T00:00:00Z", "--to", "2026-10-04T12:00:00Z"]).window, { from: at("2026-10-01T00:00:00Z"), to: at("2026-10-04T12:00:00Z") });
  // No `--repos` means "the declaration's code repositories", which only `main` can read; the flag overrides it.
  assert.equal(parseArgs(["--from", "2026-10-01T00:00:00Z", "--to", "2026-10-04T12:00:00Z"]).repos, null);
  assert.deepEqual(parseArgs(["--from", "2026-10-01T00:00:00Z", "--to", "2026-10-04T12:00:00Z", "--repos", "a/b,c/d"]).repos, ["a/b", "c/d"]);
});

// ---- the merged pull requests are read from the pull-requests LIST, never the search API --------------------------------------------------------------------
const listed = (number, mergedAt, updatedAt = mergedAt) => ({ number, created_at: "2026-10-01T00:00:00Z", merged_at: mergedAt, updated_at: updatedAt, body: null });

/** A fake `gh api` over a pull-requests list of `pulls` (newest update first), 100 to a page; it records every path it is asked for. */
function pullsList(pulls) {
  const paths = [];
  const gh = (args) => {
    paths.push(args[args.indexOf("GET") + 1]);
    const page = Number(args.find((arg) => arg.startsWith("page="))?.slice("page=".length) ?? 1);
    return pulls.slice((page - 1) * 100, page * 100);
  };
  return { gh, paths };
}

test("readMergedPulls reads repos/<repo>/pulls, keeps the pull requests merged inside the window, and never asks the search API", async () => {
  const list = pullsList([
    listed(5, "2026-10-04T14:00:00Z"), // merged after the window
    listed(4, "2026-10-04T12:00:00Z"),
    listed(3, null, "2026-10-04T11:00:00Z"), // closed unmerged
    listed(2, "2026-10-04T01:00:00Z"),
    listed(1, "2026-10-03T23:00:00Z", "2026-10-03T23:00:00Z"), // merged before it; updated before it too, so the read stops here
  ]);
  const pulls = await readMergedPulls("a11ign/a11ign", WINDOW, list.gh);
  assert.deepEqual(pulls.map((pull) => pull.number), [2, 4], "oldest merge first, whatever order the list came in");
  assert.deepEqual(pulls[0], { repo: "a11ign/a11ign", number: 2, createdAt: "2026-10-01T00:00:00Z", mergedAt: "2026-10-04T01:00:00Z", body: "" });
  assert.deepEqual(list.paths, ["repos/a11ign/a11ign/pulls"], "one page; no search/issues");
});

test("readMergedPulls refuses a window the list cannot finish in its page limit, in this tool's own flag, instead of returning part of it", async () => {
  const endless = pullsList(Array.from({ length: 3000 }, (_, index) => listed(index + 1, "2026-10-04T05:00:00Z", "2026-10-04T05:00:00Z")));
  await assert.rejects(readMergedPulls("a11ign/a11ign", WINDOW, endless.gh), /more than 3000 closed pull requests.*start --from later/);
  assert.equal(endless.paths.length, 30, "thirty pages were read, then it stopped");
});

test("readMergedPulls lets any other failure through as it came, with no flag advice added to it", async () => {
  const broken = () => { throw new Error("gh api repos/a11ign/a11ign/pulls: HTTP 403 rate limit exceeded"); };
  await assert.rejects(readMergedPulls("a11ign/a11ign", WINDOW, broken), (error) => error.message === "gh api repos/a11ign/a11ign/pulls: HTTP 403 rate limit exceeded");
});

/** The script run as a command, with `gh` replaced by a stub that runs `ghBody` and a `HOME` holding the empty sources it reads. */
function runCommand(ghBody) {
  const home = mkdtempSync(join(tmpdir(), "wakes-per-row-"));
  try {
    mkdirSync(join(home, "bin"));
    mkdirSync(join(home, ".claude", "projects"), { recursive: true });
    mkdirSync(join(home, ".cache", "a11ign"), { recursive: true });
    for (const file of ["wake-ledger", "spare-cycles"]) writeFileSync(join(home, ".cache", "a11ign", file), "");
    writeFileSync(join(home, ".cache", "a11ign", "spare-instances.json"), "{}");
    writeFileSync(join(home, "bin", "gh"), `#!/bin/sh\n${ghBody}\n`);
    chmodSync(join(home, "bin", "gh"), 0o755);
    const script = fileURLToPath(new URL("./wakes-per-row.mjs", import.meta.url));
    return spawnSync(process.execPath, [script, "--from", "2026-10-04T00:00:00Z", "--to", "2026-10-04T13:00:00Z", "--repos", "a11ign/a11ign"], {
      encoding: "utf8", timeout: 60_000, env: { ...process.env, HOME: home, PATH: `${join(home, "bin")}:${process.env.PATH}` },
    });
  } finally {
    rmSync(home, { recursive: true, force: true });
  }
}

test("run as a command it prints the reading and exits 0: the entry module's top-level await must not wait on the `trace` import that imports it back", () => {
  const run = runCommand("echo '[]'"); // an empty pull-requests list: no merged row, so no claim read either
  assert.equal(run.status, 0, `exit ${run.status}, stderr: ${run.stderr}`);
  assert.match(run.stdout, /merged rows/i, "the reading was printed");
});

test("run as a command a failed read exits 1 with the error on stderr, never 0 and never silent", () => {
  const run = runCommand("echo 'HTTP 403 rate limit exceeded' >&2; exit 1");
  assert.equal(run.status, 1, `stderr: ${run.stderr}`);
  assert.match(run.stderr, /rate limit exceeded|gh/i, "the cause is printed");
  assert.equal(run.stdout, "", "no reading is printed from a failed read");
});
